In [1]:
#!/usr/bin/env python
# coding: utf-8

import os,sys
import numpy as np
import math
import scipy
from scipy import ndimage
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input, decode_predictions
#from PIL import Image
import random
import keras
from keras.layers import Conv2D, MaxPooling2D, AveragePooling2D, Dropout, Dense, Flatten
from keras.models import Sequential
import keras.backend as K

Using TensorFlow backend.


In [2]:
print(K.image_data_format())

channels_last


In [3]:
def file2array(path, delimiter):
    recordlist = []
    fp = open(path, 'r', encoding='utf-8')
    content = fp.read()     # content现在是一行字符串，该字符串包含文件所有内容
    fp.close()
    rowlist = content.splitlines()  # 按行转换为一维表，splitlines默认参数是‘\n’
    # 逐行遍历
    # 结果按分隔符分割为行向量
    recordlist = [row.split(delimiter) for row in rowlist if row.strip()]
    return np.array(recordlist)

In [4]:
#import numpy as np
import scipy.ndimage


def ndarray_zoom_scaling(label, new_h, new_w):
    """
    Implement scaling for ndarray with scipy.ndimage.zoom
    :param label: [H, W] or [H, W, C]
    :return: label_new: [new_h, new_w] or [new_h, new_w, C]
    Examples
    --------
    ori_arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]], dtype=np.int32)
    new_arr = ndarray_zoom_scaling(ori_arr, new_h=8, new_w=10)
    >> print(new_arr)
    [[1 1 1 2 2 2 2 3 3 3]
     [1 1 1 2 2 2 2 3 3 3]
     [4 4 4 5 5 5 5 6 6 6]
     [4 4 4 5 5 5 5 6 6 6]
     [4 4 4 5 5 5 5 6 6 6]
     [4 4 4 5 5 5 5 6 6 6]
     [7 7 7 8 8 8 8 9 9 9]
     [7 7 7 8 8 8 8 9 9 9]]
    """
    scale_h = new_h / label.shape[0]
    scale_w = new_w / label.shape[1]
    if len(label.shape) == 2:
        label_new = scipy.ndimage.zoom(label, zoom=[scale_h, scale_w], order=0)
    else:
        label_new = scipy.ndimage.zoom(label, zoom=[scale_h, scale_w, 1], order=0)
    return label_new


def ndarray_nearest_neighbour_scaling(label, new_h, new_w):
    """
    Implement nearest neighbour scaling for ndarray
    :param label: [H, W] or [H, W, C]
    :return: label_new: [new_h, new_w] or [new_h, new_w, C]
    Examples
    --------
    ori_arr = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]], dtype=np.int32)
    new_arr = ndarray_nearest_neighbour_scaling(ori_arr, new_h=8, new_w=10)
    >> print(new_arr)
    [[1 1 1 1 2 2 2 3 3 3]
     [1 1 1 1 2 2 2 3 3 3]
     [1 1 1 1 2 2 2 3 3 3]
     [4 4 4 4 5 5 5 6 6 6]
     [4 4 4 4 5 5 5 6 6 6]
     [4 4 4 4 5 5 5 6 6 6]
     [7 7 7 7 8 8 8 9 9 9]
     [7 7 7 7 8 8 8 9 9 9]]
    """
#    if len(label.shape) == 2:
#        label_new = np.zeros([new_h, new_w], dtype=label.dtype)
#    else:
#        label_new = np.zeros([new_h, new_w, label.shape[2]], dtype=label.dtype)
    label_new = np.zeros([new_h, new_w, label.shape[2]], dtype=label.dtype)

    scale_h = new_h / label.shape[0]
    scale_w = new_w / label.shape[1]

    y_pos = np.arange(new_h)
    x_pos = np.arange(new_w)
    y_pos = np.floor(y_pos / scale_h).astype(np.int32)
    x_pos = np.floor(x_pos / scale_w).astype(np.int32)

    y_pos = y_pos.reshape(y_pos.shape[0], 1)
    y_pos = np.tile(y_pos, (1, new_w))
    x_pos = np.tile(x_pos, (new_h, 1))
    assert y_pos.shape == x_pos.shape

    label_new[:, :] = label[y_pos[:, :], x_pos[:, :]]
    return label_new


In [5]:
def DataSet(iFold,noise_tag,dup_tag,rand_tag):
    #
    train_path =("../Data_CNN_Indus/F%d/SECOM_samples_train_F%d") % (iFold, iFold)    
    test_path  =("../Data_CNN_Indus/F%d/SECOM_samples_test_F%d") % (iFold, iFold)
    #
    data_train = file2array(train_path, " ")
    nrow_train = data_train.shape[0]
    ncol_train = data_train.shape[1]
    #
    data_test  = file2array(test_path, " ")
    nrow_test  = data_test.shape[0]
    ncol_test  = data_test.shape[1]
    #
    if ncol_train != ncol_test:
        print('Numbers of features are not consistant.')
    if nrow_train + nrow_test != 1567:
        print('Numbers of samples are not consistant.')
    #
    train_path =("../Data_CNN_Indus/F%d/SECOM_labels_train_F%d") % (iFold, iFold)    
    test_path  =("../Data_CNN_Indus/F%d/SECOM_labels_test_F%d") % (iFold, iFold)
    #
    lab_train = file2array(train_path, " ")
    #
    lab_test  = file2array(test_path, " ")
    #
    num_feature = ncol_train
    num_class = 2
    
    tmp_cnt_per_class = np.zeros(num_class)
    for index in range(nrow_train):
        tmp = lab_train[index,0]
        tmp_cnt_per_class[(int)(tmp)] = tmp_cnt_per_class[(int)(tmp)] + 1
        
    tmp_max = tmp_cnt_per_class[0]
    tmp_ind = 0
    for index in range(num_class):
        if tmp_cnt_per_class[index] > tmp_max:
            tmp_max = tmp_cnt_per_class[index]
            tmp_ind = index
            
    num_dup = np.zeros(num_class)
    for index in range(num_class):
        if (int)(dup_tag):
            num_dup[index] = math.floor(tmp_cnt_per_class[tmp_ind]/tmp_cnt_per_class[index])
        else:
            num_dup[index] = 1
        
    nrow_train_dup = 0
    for index in range(num_class):
        nrow_train_dup = nrow_train_dup + tmp_cnt_per_class[index] * num_dup[index]
        
    nrow_train_dup = (int)(nrow_train_dup)
    
    X_train = np.empty((nrow_train_dup, num_feature), dtype=float)
    Y_train = np.empty((nrow_train_dup, num_class), dtype=float)

    sam_count = 0
    for index in range(nrow_train):
        tmp = lab_train[index,0]
        nDup = num_dup[(int)(tmp)]
        nDup = (int)(nDup)
        for iSam in range(nDup):
            tmp_cnt = 0
            for i in range(num_feature):
                X_train[sam_count,i] = float(data_train[index,i])
            sam_count = sam_count + 1

    sam_count = 0
    for index in range(nrow_train):
        tmp = lab_train[index,0]
        nDup = num_dup[(int)(tmp)]
        nDup = (int)(nDup)
        for iSam in range(nDup):
            tmp_v = np.zeros(num_class)
            tmp_v[(int)(tmp)] = 1
            Y_train[sam_count] = tmp_v
            sam_count = sam_count + 1
    
    X_test  = np.empty((nrow_test, num_feature), dtype=float)
    Y_test  = np.empty((nrow_test, num_class), dtype=float)

    for index in range(nrow_test):
        tmp_cnt = 0
        for i in range(num_feature):
            X_test[index,i] = float(data_test[index,i])
    
    for index in range(nrow_test):
        tmp = lab_test[index,0]
        tmp_v = np.zeros(num_class)
        tmp_v[(int)(tmp)] = 1
        Y_test[index] = tmp_v
        
    if (int)(noise_tag):
        noise = np.random.normal(loc=0,scale=1e-2,size=X_train.shape)
        output = X_train + noise
        X_train = np.concatenate((X_train, output), axis=0)
        Y_train = np.concatenate((Y_train, Y_train), axis=0)
    
    index = [i for i in range(len(X_train))]
    random.shuffle(index)
    X_train = X_train[index]
    Y_train = Y_train[index]
    
    index = [i for i in range(len(X_test))]
    random.shuffle(index)
    X_test = X_test[index]    
    Y_test = Y_test[index]
    
    #X_train_new = np.empty((nrow_train_dup, 224, 224, 3))
    #Y_train_new = Y_train
    
    #for index in range(nrow_train_dup):
    #    tmp_new = ndarray_nearest_neighbour_scaling(X_train[index],224,224)
    #    for c in range(3):
    #        X_train_new[index,:,:,c] = tmp_new[:,:,0]
    
    #X_test_new = np.empty((nrow_test, 224, 224, 3))
    #Y_test_new = Y_test
    
    #for index in range(nrow_test):
    #    tmp_new = ndarray_nearest_neighbour_scaling(X_test[index],224,224)
    #    for c in range(3):
    #        X_test_new[index,:,:,c] = tmp_new[:,:,0]
            
    #del X_train, X_test
    #gc.collect()

    return X_train,Y_train,X_test,Y_test

In [6]:
#import tensorflow as tf
def LeakyRelu(x, leak=0.01, name="LeakyRelu"):
   with tf.variable_scope(name):
     f1 = 0.5 * (1 + leak)
     f2 = 0.5 * (1 - leak)
     return f1 * x + f2 * tf.abs(x)

In [7]:
def neural(channel,length,classes):
    input_shape = (channel,length)
    if K.image_data_format() == "channels_last":#确认输入维度,就是channel是在开头，还是结尾
        input_shape = (length,channel)
    model = Sequential()#顺序模型（keras中包括顺序模型和函数式API两种方式）
    #model.add(Conv2D(6,(3,3),padding="valid",activation=LeakyRelu,input_shape=input_shape,name="conv1"))
    #model.add(Conv2D(6,(3,3),padding="valid",input_shape=input_shape,name="conv1"))
    #model.add(LeakyReLU(alpha=0.01))
    #model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),name="pool1"))
    #model.add(Conv2D(12,(3,3),padding="valid",activation=LeakyRelu,name="conv2",))
    #model.add(Conv2D(12,(3,3),padding="valid",name="conv2",))
    #model.add(LeakyReLU(alpha=0.01))
    #model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),name="pool2"))
    #model.add(Flatten())
    #model.add(Dense(192,activation="relu",name="fc1"))
    model.add(Dense(2400,activation=LeakyRelu,input_dim=length,name="fc1"))
    model.add(Dense(600,activation=LeakyRelu,name="fc2"))
    model.add(Dense(768,activation=LeakyRelu,name="fc3"))
    model.add(Dense(192,activation=LeakyRelu,name="fc4"))
    model.add(Dense(classes,activation="softmax",name="fc5"))
    return model


In [8]:
def get_statistics(model,sam_data,lab_data):
    num_class = 2

    #
    test_rows = len(lab_data)
    test_prc = np.zeros(num_class)
    test_rec = np.zeros(num_class)
    test_Fva = np.zeros(num_class)
    test_BER = np.zeros(num_class)
    tmp_beta = 1
    yhat_label = model.predict_classes(sam_data, batch_size=32, verbose=1)
    true_labels = np.zeros(len(lab_data))
    for index in range(len(lab_data)):
        tmp_vec = lab_data[index]
        tmp_max = tmp_vec[0]
        tmp_ind = 0
        for i in range(num_class):
            if tmp_max < tmp_vec[i]:
                tmp_max = tmp_vec[i]
                tmp_ind = i
        true_labels[index] = tmp_ind

    test_N_TP = np.zeros(num_class)
    test_N_FP = np.zeros(num_class)
    test_N_TN = np.zeros(num_class)
    test_N_FN = np.zeros(num_class)
    tmp_count = np.zeros(num_class)
    for i in range(test_rows):
        cur_label = yhat_label[i]
        true_label = true_labels[i]
        for j in range(num_class):
            if j == cur_label:
                if j == true_label:
                    test_N_TP[j]=test_N_TP[j]+1
                    tmp_count[j] = tmp_count[j] + 1
                else:
                    test_N_FP[j]=test_N_FP[j]+1
            else:
                if j == true_label:
                    test_N_FN[j]=test_N_FN[j]+1
                    tmp_count[j] = tmp_count[j] + 1
                else:
                    test_N_TN[j]=test_N_TN[j]+1

    for i in range(num_class):
        if test_N_TP[i] > 0:
            test_prc[i] = test_N_TP[i] / (test_N_TP[i] + test_N_FP[i])
        else:
            test_prc[i] = 0

        test_rec[i]= test_N_TP[i] / (test_N_TP[i] + test_N_FN[i])
        test_Fva[i]=(1 + tmp_beta*tmp_beta)*test_rec[i]*test_prc[i]/\
                      (tmp_beta*tmp_beta*(test_rec[i]+test_prc[i]))
        test_BER[i]= test_N_FN[i] / (test_N_TP[i] + test_N_FN[i])
        
    print(tmp_count)
        
    return test_N_TP,test_N_FP,test_N_TN,test_N_FN,tmp_count
    

In [9]:
all_TP_train=[]
all_FP_train=[]
all_TN_train=[]
all_FN_train=[]
all_count_train=[]
all_TP_test=[]
all_FP_test=[]
all_TN_test=[]
all_FN_test=[]
all_count_test=[]

nRun = 10
side_len = 22
num_class = 2
for noise_tag in range(2):
    for dup_tag in range(2):
        for ran_tag in range(2):
            for fold in range(nRun):
                iFold = fold + 1
                X_train,Y_train,X_test,Y_test = DataSet(iFold,noise_tag,dup_tag,ran_tag)
                print('X_train shape : ',X_train.shape)
                print('Y_train shape : ',Y_train.shape)
                print('X_test shape : ',X_test.shape)
                print('Y_test shape : ',Y_test.shape)
                #print(X_train[0])
                #print(Y_train[0,1])
                print(noise_tag,dup_tag,ran_tag,iFold)
                
                num_feature = X_train.shape[1]

                # # model
                #model = ResNet50(
                #    weights=None,
                #    classes=2
                #)

                ##
                model = neural(1,num_feature,num_class)

                model.compile(optimizer=tf.train.AdamOptimizer(0.001),
                              loss='categorical_crossentropy',
                              metrics=['accuracy'])

                # # train
                model.fit(X_train, Y_train, epochs=50, batch_size=16)

                # # evaluate
                #model.evaluate(X_test, Y_test, batch_size=32)

                # #
                #models.append(model)

                # # save
                #save_path =("./my_resnet_model.h5_F%d") % (iFold)
                #model.save(save_path)

                #
                X_train,Y_train,X_test,Y_test = DataSet(iFold,0,0,ran_tag)
                train_N_TP,train_N_FP,train_N_TN,train_N_FN,train_count = get_statistics(model,X_train,Y_train)
                test_N_TP,test_N_FP,test_N_TN,test_N_FN,test_count = get_statistics(model,X_test,Y_test)
                all_TP_train.append(train_N_TP)
                all_FP_train.append(train_N_FP)
                all_TN_train.append(train_N_TN)
                all_FN_train.append(train_N_FN)
                all_count_train.append(train_count)
                all_TP_test.append(test_N_TP)
                all_FP_test.append(test_N_FP)
                all_TN_test.append(test_N_TN)
                all_FN_test.append(test_N_FN)
                all_count_test.append(test_count)


X_train shape :  (1410, 474)
Y_train shape :  (1410, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
0 0 0 1
Epoch 1/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2760 - acc: 0.9333
Epoch 2/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2457 - acc: 0.9333
Epoch 3/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2533 - acc: 0.9333
Epoch 4/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2368 - acc: 0.9340
Epoch 5/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2341 - acc: 0.9333
Epoch 6/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2417 - acc: 0.9333
Epoch 7/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2301 - acc: 0.9326
Epoch 8/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2215 - acc: 0.9333
Epoch 9/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2121 - acc: 0.9326
Epoch 10/50

D:\toolkits.win\Anaconda3-4.4.0\envs\dlwin36-CPU\lib\site-packages\ipykernel_launcher.py:52: RuntimeWarning: invalid value encountered in double_scalars


X_train shape :  (1410, 474)
Y_train shape :  (1410, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
0 0 0 2
Epoch 1/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2948 - acc: 0.9326
Epoch 2/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2500 - acc: 0.9333
Epoch 3/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2647 - acc: 0.9333
Epoch 4/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2456 - acc: 0.9333A: 1s - l
Epoch 5/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2445 - acc: 0.9326
Epoch 6/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2268 - acc: 0.9333
Epoch 7/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2733 - acc: 0.9333
Epoch 8/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 9/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333A: 

1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333A: 1s - los
Epoch 31/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 32/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 33/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 34/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 35/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 36/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 37/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 38/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 39/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 40/50
1410/1410

1410/1410 [==============================] - 2s 1ms/step - loss: 0.2115 - acc: 0.9340
Epoch 8/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2135 - acc: 0.9340
Epoch 9/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2013 - acc: 0.9348
Epoch 10/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2500 - acc: 0.9376
Epoch 11/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 12/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 13/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 14/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 15/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 16/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 17/50
1410/1410 [===========

1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 38/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 39/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 40/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 41/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 42/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 43/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 44/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 45/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 46/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0631 - acc: 0.9340
Epoch 47/50
1410/1410 [=========

1411/1411 [==============================] - 2s 1ms/step - loss: 0.1961 - acc: 0.9355
Epoch 14/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1851 - acc: 0.9355
Epoch 15/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1995 - acc: 0.9383
Epoch 16/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1919 - acc: 0.9355
Epoch 17/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1791 - acc: 0.9433
Epoch 18/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.2127 - acc: 0.9405
Epoch 19/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.2104 - acc: 0.9334
Epoch 20/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1872 - acc: 0.9376
Epoch 21/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.2277 - acc: 0.9320
Epoch 22/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1984 - acc: 0.9341
Epoch 23/50
1411/1411 [=========

1411/1411 [==============================] - 2s 2ms/step - loss: 0.1894 - acc: 0.9405
Epoch 45/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1661 - acc: 0.9391
Epoch 46/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1449 - acc: 0.9454
Epoch 47/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1408 - acc: 0.9490
Epoch 48/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1326 - acc: 0.9490
Epoch 49/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1465 - acc: 0.9468
Epoch 50/50
1411/1411 [==============================] - 0s 330us/step
[1317.   94.]
156/156 [==============================] - 0s 275us/step
[146.  10.]
X_train shape :  (1411, 474)
Y_train shape :  (1411, 2)
X_test shape :  (156, 474)
Y_test shape :  (156, 2)
0 0 0 10
Epoch 1/50
1411/1411 [==============================] - 3s 2ms/step - loss: 0.2780 - acc: 0.9220
Epoch 2/50
1411/1411 [==============================] - 

1410/1410 [==============================] - 2s 2ms/step - loss: 0.1961 - acc: 0.9355
Epoch 23/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2062 - acc: 0.9333
Epoch 24/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1825 - acc: 0.9362
Epoch 25/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1886 - acc: 0.9319
Epoch 26/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1724 - acc: 0.9404
Epoch 27/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1867 - acc: 0.9418
Epoch 28/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.6337 - acc: 0.9390
Epoch 29/50
1410/1410 [==============================] - 2s 2ms/step - loss: 1.0745 - acc: 0.9333
Epoch 30/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 31/50
1410/1410 [==============================] - 2s 1ms/step - loss: 1.0745 - acc: 0.9333
Epoch 32/50
1410/1410 [=========

1410/1410 [==============================] - 0s 312us/step
[1316.   94.]
157/157 [==============================] - 0s 241us/step
[147.  10.]
X_train shape :  (1410, 474)
Y_train shape :  (1410, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
0 0 1 3
Epoch 1/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2712 - acc: 0.9284
Epoch 2/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2644 - acc: 0.9333
Epoch 3/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2410 - acc: 0.9333
Epoch 4/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2293 - acc: 0.9333
Epoch 5/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2312 - acc: 0.9333
Epoch 6/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2378 - acc: 0.9333
Epoch 7/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2088 - acc: 0.9319
Epoch 8/50
1410/1410 [==============================] - 2s 1ms/

1410/1410 [==============================] - 2s 1ms/step - loss: 0.1897 - acc: 0.9340
Epoch 27/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1856 - acc: 0.9411
Epoch 28/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1995 - acc: 0.9390
Epoch 29/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1744 - acc: 0.9426
Epoch 30/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1671 - acc: 0.9376
Epoch 31/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.2092 - acc: 0.9390A: 1s - loss: 0.16
Epoch 32/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1686 - acc: 0.9411A: 1s - loss
Epoch 33/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1760 - acc: 0.9376
Epoch 34/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1569 - acc: 0.9426
Epoch 35/50
1410/1410 [==============================] - 2s 1ms/step - loss: 0.1711 - acc: 0.9369
Ep

1410/1410 [==============================] - 2s 2ms/step - loss: 0.2403 - acc: 0.9340
Epoch 5/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2421 - acc: 0.9340
Epoch 6/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2292 - acc: 0.9340
Epoch 7/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2371 - acc: 0.9340
Epoch 8/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2116 - acc: 0.9340
Epoch 9/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2109 - acc: 0.9340
Epoch 10/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2033 - acc: 0.9340
Epoch 11/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1931 - acc: 0.9333
Epoch 12/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2007 - acc: 0.9340
Epoch 13/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1904 - acc: 0.9340A: 1s - lo
Epoch 14/50
1410/1410 [====

1410/1410 [==============================] - 2s 2ms/step - loss: 0.1679 - acc: 0.9418
Epoch 34/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1730 - acc: 0.9475
Epoch 35/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.2140 - acc: 0.9333
Epoch 36/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1765 - acc: 0.9390
Epoch 37/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1782 - acc: 0.9404
Epoch 38/50
1410/1410 [==============================] - 2s 2ms/step - loss: 0.1645 - acc: 0.9447
Epoch 39/50
1410/1410 [==============================] - 3s 2ms/step - loss: 0.1581 - acc: 0.9482
Epoch 40/50
1410/1410 [==============================] - 3s 2ms/step - loss: 0.1706 - acc: 0.9426
Epoch 41/50
1410/1410 [==============================] - 3s 2ms/step - loss: 0.1762 - acc: 0.9447
Epoch 42/50
1410/1410 [==============================] - 3s 2ms/step - loss: 0.1638 - acc: 0.9461
Epoch 43/50
1410/1410 [=========

1411/1411 [==============================] - 2s 2ms/step - loss: 0.1914 - acc: 0.9334
Epoch 12/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1932 - acc: 0.9348
Epoch 13/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1919 - acc: 0.9327
Epoch 14/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.2127 - acc: 0.9362
Epoch 15/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.2070 - acc: 0.9320
Epoch 16/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1874 - acc: 0.9327
Epoch 17/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1959 - acc: 0.9376
Epoch 18/50
1411/1411 [==============================] - 2s 1ms/step - loss: 0.1743 - acc: 0.9405
Epoch 19/50
1411/1411 [==============================] - 3s 2ms/step - loss: 0.1728 - acc: 0.9440
Epoch 20/50
1411/1411 [==============================] - 3s 2ms/step - loss: 0.1859 - acc: 0.9362
Epoch 21/50
1411/1411 [=========

1411/1411 [==============================] - 3s 2ms/step - loss: 0.1640 - acc: 0.9398
Epoch 43/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1439 - acc: 0.9461
Epoch 44/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1584 - acc: 0.9440
Epoch 45/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1555 - acc: 0.9391
Epoch 46/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1439 - acc: 0.9497
Epoch 47/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1537 - acc: 0.9454
Epoch 48/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1383 - acc: 0.9525
Epoch 49/50
1411/1411 [==============================] - 2s 2ms/step - loss: 0.1489 - acc: 0.9483
Epoch 50/50
1411/1411 [==============================] - 1s 484us/step
[1317.   94.]
156/156 [==============================] - 0s 307us/step
[146.  10.]
X_train shape :  (2632, 474)
Y_train shape :  (2632, 2)
X_test shape :  (1

2632/2632 [==============================] - 4s 2ms/step - loss: 0.0788 - acc: 0.9749
Epoch 21/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1228 - acc: 0.9590
Epoch 22/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1068 - acc: 0.9658
Epoch 23/50
2632/2632 [==============================] - 4s 1ms/step - loss: 0.0629 - acc: 0.9783
Epoch 24/50
2632/2632 [==============================] - 4s 1ms/step - loss: 0.1222 - acc: 0.9574
Epoch 25/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1224 - acc: 0.9574
Epoch 26/50
2632/2632 [==============================] - 4s 1ms/step - loss: 0.1682 - acc: 0.9445
Epoch 27/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.0541 - acc: 0.9848
Epoch 28/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1572 - acc: 0.9464
Epoch 29/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.0346 - acc: 0.9924
Epoch 30/50
2632/2632 [=========

2632/2632 [==============================] - 4s 1ms/step - loss: 0.1161 - acc: 0.9654A: 0s - loss: 0.1366 - ac
Epoch 50/50
1410/1410 [==============================] - 1s 399us/step
[1316.   94.]
157/157 [==============================] - 0s 235us/step
[147.  10.]
X_train shape :  (2619, 474)
Y_train shape :  (2619, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
0 1 0 4
Epoch 1/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.6970 - acc: 0.5472A: 0s - loss: 0.6995 -
Epoch 2/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.5864 - acc: 0.6686
Epoch 3/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4708 - acc: 0.7866
Epoch 4/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4364 - acc: 0.8026A: 0s - loss: 0.4401 - acc: 0.798 - ETA: 0s - loss: 0.4412 - acc: 
Epoch 5/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4273 - acc: 0.7961
Epoch 6/50
2619/2619 [========================

2619/2619 [==============================] - 4s 1ms/step - loss: 0.1482 - acc: 0.9507
Epoch 24/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1008 - acc: 0.9668
Epoch 25/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1068 - acc: 0.9626
Epoch 26/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1465 - acc: 0.9481
Epoch 27/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1155 - acc: 0.9607
Epoch 28/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1575 - acc: 0.9485
Epoch 29/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0869 - acc: 0.9695
Epoch 30/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.1178 - acc: 0.9607
Epoch 31/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0729 - acc: 0.9756
Epoch 32/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0667 - acc: 0.9809
Epoch 33/50
2619/2619 [=========

Epoch 1/50
2619/2619 [==============================] - 5s 2ms/step - loss: 0.6799 - acc: 0.5811
Epoch 2/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.5854 - acc: 0.6770
Epoch 3/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4715 - acc: 0.7698
Epoch 4/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4141 - acc: 0.8045
Epoch 5/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.4268 - acc: 0.7969
Epoch 6/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.3468 - acc: 0.8572
Epoch 7/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.3098 - acc: 0.8660A: 2s - loss: 0.3440 - ETA: 2s - loss: 0.3159 - acc: 0.86 - ETA: 1s
Epoch 8/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.2849 - acc: 0.8889
Epoch 9/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.2543 - acc: 0.8977
Epoch 10/50
2619/2619 [==============================] - 4s 

2633/2633 [==============================] - 4s 2ms/step - loss: 0.1822 - acc: 0.9396
Epoch 31/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.1366 - acc: 0.9521
Epoch 32/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.0560 - acc: 0.9848
Epoch 33/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0767 - acc: 0.9776
Epoch 34/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0438 - acc: 0.9905
Epoch 35/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.1776 - acc: 0.9423
Epoch 36/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0773 - acc: 0.9803
Epoch 37/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0714 - acc: 0.9795
Epoch 38/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0834 - acc: 0.9761
Epoch 39/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0752 - acc: 0.9814
Epoch 40/50
2633/2633 [=========

2633/2633 [==============================] - 5s 2ms/step - loss: 0.3434 - acc: 0.8557
Epoch 9/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3702 - acc: 0.8416
Epoch 10/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2828 - acc: 0.8948
Epoch 11/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2668 - acc: 0.8952
Epoch 12/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2291 - acc: 0.9138
Epoch 13/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2974 - acc: 0.8735
Epoch 14/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2274 - acc: 0.9104
Epoch 15/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2336 - acc: 0.9115
Epoch 16/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.1693 - acc: 0.9408
Epoch 17/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.1425 - acc: 0.9506
Epoch 18/50
2633/2633 [==========

2632/2632 [==============================] - 5s 2ms/step - loss: 0.0032 - acc: 0.9992
Epoch 40/50
2632/2632 [==============================] - 5s 2ms/step - loss: 8.2486e-05 - acc: 1.0000
Epoch 41/50
2632/2632 [==============================] - 5s 2ms/step - loss: 3.9186e-05 - acc: 1.0000
Epoch 42/50
2632/2632 [==============================] - 4s 2ms/step - loss: 2.4645e-05 - acc: 1.0000
Epoch 43/50
2632/2632 [==============================] - 4s 2ms/step - loss: 1.6902e-05 - acc: 1.0000
Epoch 44/50
2632/2632 [==============================] - 5s 2ms/step - loss: 1.2721e-05 - acc: 1.0000
Epoch 45/50
2632/2632 [==============================] - 5s 2ms/step - loss: 9.9866e-06 - acc: 1.0000
Epoch 46/50
2632/2632 [==============================] - 5s 2ms/step - loss: 7.9039e-06 - acc: 1.0000
Epoch 47/50
2632/2632 [==============================] - 5s 2ms/step - loss: 6.5003e-06 - acc: 1.0000
Epoch 48/50
2632/2632 [==============================] - 5s 2ms/step - loss: 5.3464e-06 - acc: 1.0

2632/2632 [==============================] - 4s 2ms/step - loss: 0.2533 - acc: 0.8978
Epoch 17/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.2488 - acc: 0.9050
Epoch 18/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1944 - acc: 0.9339
Epoch 19/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1716 - acc: 0.9430
Epoch 20/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1935 - acc: 0.9274
Epoch 21/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1614 - acc: 0.9403
Epoch 22/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.2084 - acc: 0.9388
Epoch 23/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1786 - acc: 0.9396
Epoch 24/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1437 - acc: 0.9529
Epoch 25/50
2632/2632 [==============================] - 4s 2ms/step - loss: 0.1077 - acc: 0.9639
Epoch 26/50
2632/2632 [=========

2619/2619 [==============================] - 4s 1ms/step - loss: 0.0708 - acc: 0.9790
Epoch 47/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0076 - acc: 0.9985
Epoch 48/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0634 - acc: 0.9790
Epoch 49/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.0230 - acc: 0.9920
Epoch 50/50
1410/1410 [==============================] - 1s 514us/step
[1317.   93.]
157/157 [==============================] - 0s 267us/step
[146.  11.]
X_train shape :  (2619, 474)
Y_train shape :  (2619, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
0 1 1 5
Epoch 1/50
2619/2619 [==============================] - 5s 2ms/step - loss: 0.6553 - acc: 0.5914
Epoch 2/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.4937 - acc: 0.7526
Epoch 3/50
2619/2619 [==============================] - 4s 1ms/step - loss: 0.5121 - acc: 0.7514
Epoch 4/50
2619/2619 [==============================] - 4s 

2619/2619 [==============================] - 4s 2ms/step - loss: 0.0598 - acc: 0.9809
Epoch 25/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.0835 - acc: 0.9691
Epoch 26/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.1259 - acc: 0.9633
Epoch 27/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.0735 - acc: 0.9801
Epoch 28/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.0876 - acc: 0.9706
Epoch 29/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.0309 - acc: 0.9927
Epoch 30/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.1828 - acc: 0.9443
Epoch 31/50
2619/2619 [==============================] - 5s 2ms/step - loss: 0.0931 - acc: 0.9702
Epoch 32/50
2619/2619 [==============================] - ETA: 0s - loss: 0.0317 - acc: 0.991 - 4s 2ms/step - loss: 0.0314 - acc: 0.9912
Epoch 33/50
2619/2619 [==============================] - 4s 2ms/step - loss: 0.0233 - acc: 0

2633/2633 [==============================] - 6s 2ms/step - loss: 0.6783 - acc: 0.5742
Epoch 2/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.5502 - acc: 0.7079
Epoch 3/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.4397 - acc: 0.7938
Epoch 4/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.4227 - acc: 0.8025
Epoch 5/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3581 - acc: 0.8428
Epoch 6/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3575 - acc: 0.8450
Epoch 7/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3839 - acc: 0.8196
Epoch 8/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3347 - acc: 0.8545
Epoch 9/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.3120 - acc: 0.8705
Epoch 10/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.2981 - acc: 0.8788
Epoch 11/50
2633/2633 [=================

2633/2633 [==============================] - 4s 2ms/step - loss: 0.0413 - acc: 0.9886
Epoch 33/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0620 - acc: 0.9787
Epoch 34/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0666 - acc: 0.9829
Epoch 35/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.1272 - acc: 0.9677
Epoch 36/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0374 - acc: 0.9897
Epoch 37/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0391 - acc: 0.9890
Epoch 38/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0566 - acc: 0.9814
Epoch 39/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0220 - acc: 0.9958
Epoch 40/50
2633/2633 [==============================] - 4s 2ms/step - loss: 0.0457 - acc: 0.9852
Epoch 41/50
2633/2633 [==============================] - 5s 2ms/step - loss: 0.0364 - acc: 0.9909
Epoch 42/50
2633/2633 [=========

2820/2820 [==============================] - 5s 2ms/step - loss: 0.1862 - acc: 0.9365
Epoch 11/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1772 - acc: 0.9390
Epoch 12/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1885 - acc: 0.9422
Epoch 13/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1830 - acc: 0.9401
Epoch 14/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1801 - acc: 0.9433
Epoch 15/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1731 - acc: 0.9422
Epoch 16/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1646 - acc: 0.9447
Epoch 17/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1606 - acc: 0.9461
Epoch 18/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2007 - acc: 0.9383
Epoch 19/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1602 - acc: 0.9461
Epoch 20/50
2820/2820 [=========

2820/2820 [==============================] - 5s 2ms/step - loss: 0.0966 - acc: 0.9670
Epoch 42/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0848 - acc: 0.9695
Epoch 43/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0630 - acc: 0.9780
Epoch 44/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0945 - acc: 0.9663
Epoch 45/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0903 - acc: 0.9674
Epoch 46/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0656 - acc: 0.9773
Epoch 47/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0348 - acc: 0.9340
Epoch 48/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0745 - acc: 0.9333
Epoch 49/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0745 - acc: 0.9333
Epoch 50/50
1410/1410 [==============================] - 1s 658us/step
[1316.   94.]
157/157 [==============================] - 0s

2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 20/50
2820/2820 [==============================] - 4s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 21/50
2820/2820 [==============================] - 4s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 22/50
2820/2820 [==============================] - 4s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 23/50
2820/2820 [==============================] - 4s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 24/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 25/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 26/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340A: 0s - loss: 1.0775 - ac
Epoch 27/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 28/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 2

2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 50/50
1410/1410 [==============================] - 1s 742us/step
[1317.   93.]
157/157 [==============================] - 0s 343us/step
[146.  11.]
X_train shape :  (2820, 468)
Y_train shape :  (2820, 2)
X_test shape :  (157, 468)
Y_test shape :  (157, 2)
1 0 0 6
Epoch 1/50
2820/2820 [==============================] - 7s 3ms/step - loss: 0.2675 - acc: 0.9340
Epoch 2/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2350 - acc: 0.9340
Epoch 3/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2301 - acc: 0.9344
Epoch 4/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2314 - acc: 0.9340
Epoch 5/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2087 - acc: 0.9333
Epoch 6/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1987 - acc: 0.9355
Epoch 7/50
2820/2820 [==============================] - 5s 2ms

2820/2820 [==============================] - 5s 2ms/step - loss: 0.1277 - acc: 0.9539
Epoch 28/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1483 - acc: 0.9514
Epoch 29/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1530 - acc: 0.9500
Epoch 30/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1468 - acc: 0.9504
Epoch 31/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2153 - acc: 0.9504
Epoch 32/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1576 - acc: 0.9468
Epoch 33/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1392 - acc: 0.9546
Epoch 34/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1538 - acc: 0.9500
Epoch 35/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1253 - acc: 0.9567
Epoch 36/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1439 - acc: 0.9443
Epoch 37/50
2820/2820 [=========

2822/2822 [==============================] - 5s 2ms/step - loss: 0.2396 - acc: 0.9323
Epoch 6/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.2336 - acc: 0.9334
Epoch 7/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.2409 - acc: 0.9334
Epoch 8/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.2176 - acc: 0.9344
Epoch 9/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1982 - acc: 0.9337
Epoch 10/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1922 - acc: 0.9344
Epoch 11/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1943 - acc: 0.9387
Epoch 12/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.2143 - acc: 0.9362
Epoch 13/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1904 - acc: 0.9355
Epoch 14/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1961 - acc: 0.9352
Epoch 15/50
2822/2822 [=============

2822/2822 [==============================] - 5s 2ms/step - loss: 0.1107 - acc: 0.9685
Epoch 36/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1484 - acc: 0.9617
Epoch 37/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1567 - acc: 0.9454
Epoch 38/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0843 - acc: 0.9709
Epoch 39/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0812 - acc: 0.9727
Epoch 40/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0832 - acc: 0.9724
Epoch 41/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0616 - acc: 0.9787
Epoch 42/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0809 - acc: 0.9741
Epoch 43/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0673 - acc: 0.9823
Epoch 44/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.0249 - acc: 0.9915
Epoch 45/50
2822/2822 [=========

2820/2820 [==============================] - 5s 2ms/step - loss: 0.1921 - acc: 0.9369
Epoch 14/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1906 - acc: 0.9372
Epoch 15/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1692 - acc: 0.9351
Epoch 16/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1647 - acc: 0.9408
Epoch 17/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1717 - acc: 0.9411
Epoch 18/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1607 - acc: 0.9447
Epoch 19/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.2012 - acc: 0.9344
Epoch 20/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1675 - acc: 0.9411
Epoch 21/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1526 - acc: 0.9450
Epoch 22/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1996 - acc: 0.9358
Epoch 23/50
2820/2820 [=========

2820/2820 [==============================] - 5s 2ms/step - loss: 0.0757 - acc: 0.9738
Epoch 44/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0582 - acc: 0.9805
Epoch 45/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0479 - acc: 0.9844
Epoch 46/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0435 - acc: 0.9844
Epoch 47/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0341 - acc: 0.9862
Epoch 48/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0776 - acc: 0.9741
Epoch 49/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1830 - acc: 0.9660
Epoch 50/50
1410/1410 [==============================] - 1s 732us/step
[1316.   94.]
157/157 [==============================] - 0s 273us/step
[147.  10.]
X_train shape :  (2820, 474)
Y_train shape :  (2820, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
1 0 1 4
Epoch 1/50
2820/2820 [==============================] - 

2820/2820 [==============================] - 6s 2ms/step - loss: 0.1429 - acc: 0.9447
Epoch 22/50
2820/2820 [==============================] - 6s 2ms/step - loss: 0.1411 - acc: 0.9479
Epoch 23/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1304 - acc: 0.9511
Epoch 24/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1302 - acc: 0.9532
Epoch 25/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1222 - acc: 0.9567
Epoch 26/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1606 - acc: 0.9440
Epoch 27/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1165 - acc: 0.9578
Epoch 28/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.1143 - acc: 0.9532
Epoch 29/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.0975 - acc: 0.9656
Epoch 30/50
2820/2820 [==============================] - 5s 2ms/step - loss: 0.9607 - acc: 0.9348
Epoch 31/50
2820/2820 [=========

157/157 [==============================] - 0s 292us/step
[146.  11.]
X_train shape :  (2820, 474)
Y_train shape :  (2820, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
1 0 1 7
Epoch 1/50
2820/2820 [==============================] - 6s 2ms/step - loss: 1.0667 - acc: 0.9337
Epoch 2/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 3/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 4/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 5/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 6/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 7/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 8/50
2820/2820 [==============================] - 5s 2ms/step - loss: 1.0631 - acc: 0.9340
Epoch 9/50
2820/2820 [=================

2822/2822 [==============================] - 5s 2ms/step - loss: 0.1208 - acc: 0.9596
Epoch 31/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.6368 - acc: 0.9458
Epoch 32/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 33/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 34/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 35/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 36/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 37/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 38/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 39/50
2822/2822 [==============================] - 5s 2ms/step - loss: 1.0738 - acc: 0.9334
Epoch 40/50
2822/2822 [=========

2822/2822 [==============================] - 5s 2ms/step - loss: 0.1914 - acc: 0.9316
Epoch 9/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1953 - acc: 0.9334
Epoch 10/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1904 - acc: 0.9337
Epoch 11/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1763 - acc: 0.9313
Epoch 12/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1810 - acc: 0.9337
Epoch 13/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1924 - acc: 0.9309
Epoch 14/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1718 - acc: 0.9352
Epoch 15/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1859 - acc: 0.9394
Epoch 16/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1746 - acc: 0.9369
Epoch 17/50
2822/2822 [==============================] - 5s 2ms/step - loss: 0.1514 - acc: 0.9447
Epoch 18/50
2822/2822 [==========

5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 40/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 41/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 42/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 43/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 44/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 45/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 46/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 47/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 48/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0061 - acc: 0.9996
Epoch 49/50
5264/5264 [=========

5264/5264 [==============================] - 9s 2ms/step - loss: 0.1209 - acc: 0.9576
Epoch 18/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0721 - acc: 0.9776
Epoch 19/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0418 - acc: 0.9865
Epoch 20/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0868 - acc: 0.9692
Epoch 21/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0433 - acc: 0.9837
Epoch 22/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0242 - acc: 0.9926
Epoch 23/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0430 - acc: 0.9875
Epoch 24/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0792 - acc: 0.9755
Epoch 25/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0273 - acc: 0.9894
Epoch 26/50
5264/5264 [==============================] - 9s 2ms/step - loss: 0.0452 - acc: 0.9905
Epoch 27/50
5264/5264 [=========

5238/5238 [==============================] - 9s 2ms/step - loss: 1.2961e-07 - acc: 1.0000
Epoch 47/50
5238/5238 [==============================] - 9s 2ms/step - loss: 1.2958e-07 - acc: 1.0000
Epoch 48/50
5238/5238 [==============================] - 9s 2ms/step - loss: 1.2598e-07 - acc: 1.0000
Epoch 49/50
5238/5238 [==============================] - 9s 2ms/step - loss: 1.2563e-07 - acc: 1.0000
Epoch 50/50
1410/1410 [==============================] - 1s 853us/step
[1317.   93.]
157/157 [==============================] - 0s 292us/step
[146.  11.]
X_train shape :  (5238, 474)
Y_train shape :  (5238, 2)
X_test shape :  (157, 474)
Y_test shape :  (157, 2)
1 1 0 5
Epoch 1/50
5238/5238 [==============================] - 11s 2ms/step - loss: 0.6308 - acc: 0.6224
Epoch 2/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.4533 - acc: 0.7774
Epoch 3/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.3779 - acc: 0.8370
Epoch 4/50
5238/5238 [====================

5238/5238 [==============================] - 9s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 24/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 25/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 26/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0062 - acc: 0.9996A: 0s - loss: 0.0063 - acc: 0
Epoch 27/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 28/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 29/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 30/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 31/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0062 - acc: 0.9996
Epoch 32/50
5238/5238 [==============================] - 10s 2ms/step - loss: 0.0062 - acc: 0.9996
Ep

Epoch 1/50
5266/5266 [==============================] - 11s 2ms/step - loss: 0.6067 - acc: 0.6455
Epoch 2/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.4652 - acc: 0.7733
Epoch 3/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.3737 - acc: 0.8304
Epoch 4/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.3684 - acc: 0.8407
Epoch 5/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.3162 - acc: 0.8654
Epoch 6/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.2770 - acc: 0.8925
Epoch 7/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.2527 - acc: 0.8963
Epoch 8/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.2422 - acc: 0.9077
Epoch 9/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.1789 - acc: 0.9295
Epoch 10/50
5266/5266 [==============================] - 9s 2ms/step - loss: 0.1508 - acc: 0.9457
Epoch 11/50
5266/5266 [=====

5266/5266 [==============================] - 10s 2ms/step - loss: 1.7040e-07 - acc: 1.0000
Epoch 32/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.6216e-07 - acc: 1.0000
Epoch 33/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.5171e-07 - acc: 1.0000
Epoch 34/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.4589e-07 - acc: 1.0000
Epoch 35/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.3942e-07 - acc: 1.0000
Epoch 36/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.3839e-07 - acc: 1.0000
Epoch 37/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.3049e-07 - acc: 1.0000
Epoch 38/50
5266/5266 [==============================] - 11s 2ms/step - loss: 1.3200e-07 - acc: 1.0000
Epoch 39/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.2775e-07 - acc: 1.0000
Epoch 40/50
5266/5266 [==============================] - 10s 2ms/step - loss: 1.3142e

5264/5264 [==============================] - 8s 2ms/step - loss: 0.2005 - acc: 0.9246
Epoch 9/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.1453 - acc: 0.9491
Epoch 10/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.1397 - acc: 0.9498
Epoch 11/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0878 - acc: 0.9694A: 1s - loss: 
Epoch 12/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0818 - acc: 0.9704
Epoch 13/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0530 - acc: 0.9827
Epoch 14/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0755 - acc: 0.9763
Epoch 15/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.1004 - acc: 0.9668
Epoch 16/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0528 - acc: 0.9823
Epoch 17/50
5264/5264 [==============================] - 8s 2ms/step - loss: 0.0788 - acc: 0.9761
Epoch 18/50
5264/52

5264/5264 [==============================] - 8s 2ms/step - loss: 2.7408e-07 - acc: 1.0000
Epoch 37/50
5264/5264 [==============================] - 8s 2ms/step - loss: 2.3483e-07 - acc: 1.0000
Epoch 38/50
5264/5264 [==============================] - 8s 2ms/step - loss: 2.0753e-07 - acc: 1.0000
Epoch 39/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.8655e-07 - acc: 1.0000
Epoch 40/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.7673e-07 - acc: 1.0000
Epoch 41/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.6468e-07 - acc: 1.0000A: 
Epoch 42/50
5264/5264 [==============================] - 9s 2ms/step - loss: 1.5526e-07 - acc: 1.0000
Epoch 43/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.5345e-07 - acc: 1.0000
Epoch 44/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.4364e-07 - acc: 1.0000
Epoch 45/50
5264/5264 [==============================] - 8s 2ms/step - loss: 1.4234e-07 - a

5238/5238 [==============================] - 8s 2ms/step - loss: 0.3284 - acc: 0.8597
Epoch 12/50
5238/5238 [==============================] - 10s 2ms/step - loss: 0.2381 - acc: 0.9143
Epoch 13/50
5238/5238 [==============================] - 10s 2ms/step - loss: 0.1988 - acc: 0.9273
Epoch 14/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.1378 - acc: 0.9549
Epoch 15/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.1158 - acc: 0.9607
Epoch 16/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.1165 - acc: 0.9603
Epoch 17/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.1020 - acc: 0.9662
Epoch 18/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.1120 - acc: 0.9622
Epoch 19/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0819 - acc: 0.9756
Epoch 20/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0613 - acc: 0.9813
Epoch 21/50
5238/5238 [=======

5238/5238 [==============================] - 8s 2ms/step - loss: 2.6194e-06 - acc: 1.0000
Epoch 41/50
5238/5238 [==============================] - 8s 2ms/step - loss: 1.5921e-06 - acc: 1.0000
Epoch 42/50
5238/5238 [==============================] - 8s 2ms/step - loss: 1.0781e-06 - acc: 1.0000
Epoch 43/50
5238/5238 [==============================] - 8s 2ms/step - loss: 8.0007e-07 - acc: 1.0000
Epoch 44/50
5238/5238 [==============================] - 8s 2ms/step - loss: 6.1563e-07 - acc: 1.0000
Epoch 45/50
5238/5238 [==============================] - 8s 2ms/step - loss: 4.7462e-07 - acc: 1.0000
Epoch 46/50
5238/5238 [==============================] - 8s 2ms/step - loss: 4.2201e-07 - acc: 1.0000
Epoch 47/50
5238/5238 [==============================] - 9s 2ms/step - loss: 3.6602e-07 - acc: 1.0000
Epoch 48/50
5238/5238 [==============================] - 9s 2ms/step - loss: 3.0641e-07 - acc: 1.0000
Epoch 49/50
5238/5238 [==============================] - 8s 2ms/step - loss: 2.6801e-07 - acc:

5238/5238 [==============================] - 8s 2ms/step - loss: 0.0527 - acc: 0.9836
Epoch 17/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0464 - acc: 0.9836
Epoch 18/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0458 - acc: 0.9828
Epoch 19/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0430 - acc: 0.9866
Epoch 20/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0271 - acc: 0.9906
Epoch 21/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0163 - acc: 0.9956
Epoch 22/50
5238/5238 [==============================] - 9s 2ms/step - loss: 0.0508 - acc: 0.9842
Epoch 23/50
5238/5238 [==============================] - 8s 2ms/step - loss: 0.0234 - acc: 0.9906
Epoch 24/50
5238/5238 [==============================] - 8s 2ms/step - loss: 1.5199e-04 - acc: 1.0000
Epoch 25/50
5238/5238 [==============================] - 8s 2ms/step - loss: 1.2155e-05 - acc: 1.0000
Epoch 26/50
5238/5238 [=

5266/5266 [==============================] - 9s 2ms/step - loss: 6.0661e-07 - acc: 1.0000
Epoch 44/50
5266/5266 [==============================] - 9s 2ms/step - loss: 4.9208e-07 - acc: 1.0000
Epoch 45/50
5266/5266 [==============================] - 8s 2ms/step - loss: 4.2224e-07 - acc: 1.0000
Epoch 46/50
5266/5266 [==============================] - 8s 2ms/step - loss: 3.6008e-07 - acc: 1.0000
Epoch 47/50
5266/5266 [==============================] - 8s 2ms/step - loss: 3.1367e-07 - acc: 1.0000
Epoch 48/50
5266/5266 [==============================] - 8s 2ms/step - loss: 2.7058e-07 - acc: 1.0000
Epoch 49/50
5266/5266 [==============================] - 8s 2ms/step - loss: 2.3660e-07 - acc: 1.0000
Epoch 50/50
1411/1411 [==============================] - 1s 927us/step
[1317.   94.]
156/156 [==============================] - 0s 275us/step
[146.  10.]
X_train shape :  (5266, 474)
Y_train shape :  (5266, 2)
X_test shape :  (156, 474)
Y_test shape :  (156, 2)
1 1 1 9
Epoch 1/50
5266/5266 [======

Epoch 21/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0307 - acc: 0.9907
Epoch 22/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0660 - acc: 0.9795
Epoch 23/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0326 - acc: 0.9877
Epoch 24/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0525 - acc: 0.9789
Epoch 25/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0331 - acc: 0.9884
Epoch 26/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0189 - acc: 0.9941
Epoch 27/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0633 - acc: 0.9827
Epoch 28/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0151 - acc: 0.9956
Epoch 29/50
5266/5266 [==============================] - 8s 2ms/step - loss: 0.0156 - acc: 0.9951
Epoch 30/50
5266/5266 [==============================] - 8s 1ms/step - loss: 0.2112 - acc: 0.9392
Epoch 31/50
5266/526

In [10]:
noise = np.random.normal(loc=0,scale=1e-2,size=X_train.shape)
output = X_train + noise
X_train_all = np.concatenate((X_train, output), axis=0)
print(noise)
print(noise.shape)
print(output.shape)
print(X_train.shape)
print(X_train_all.shape)
for i in range(len(X_train)):
    if (X_train[i]==X_train_all[i]).all()==False:
        print(i)
for i in range(len(X_train)):
    ind = len(X_train)+i
    if (output[i]==X_train_all[ind]).all()==False:
        print(ind)
        

[[ 0.01514813  0.01492755  0.01486372 ...  0.00857476 -0.00436995
  -0.00757773]
 [-0.00032011  0.00909576  0.0037819  ...  0.01969244  0.00399345
  -0.01421445]
 [-0.00353804  0.00738441  0.00642808 ...  0.00350748  0.01241723
   0.01060618]
 ...
 [ 0.00410879  0.01063525 -0.01757033 ...  0.00444562 -0.00209475
  -0.00322124]
 [-0.00043965  0.01629578  0.00783747 ...  0.00279593 -0.00999914
  -0.01270919]
 [ 0.01259797  0.0029113   0.00486612 ...  0.00593103 -0.01530847
   0.00264231]]
(1411, 474)
(1411, 474)
(1411, 474)
(2822, 474)


In [11]:
for noise_tag in range(2):
    for dup_tag in range(2):
        for ran_tag in range(2):
            for iRun in range(nRun):
                print(all_TP_train[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_FP_train[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_TN_train[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_FN_train[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
            for iRun in range(nRun):
                print(all_TP_test[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_FP_test[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_TN_test[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_FN_test[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])

for noise_tag in range(2):
    for dup_tag in range(2):
        for ran_tag in range(2):
            for iRun in range(nRun):
                print(all_count_train[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])
                print(all_count_test[noise_tag*2*2*nRun+dup_tag*2*nRun+ran_tag*nRun+iRun])


[1316.    0.]
[94.  0.]
[   0. 1316.]
[ 0. 94.]
[1316.    0.]
[94.  0.]
[   0. 1316.]
[ 0. 94.]
[1316.    0.]
[94.  0.]
[   0. 1316.]
[ 0. 94.]
[1317.    0.]
[93.  0.]
[   0. 1317.]
[ 0. 93.]
[1317.    0.]
[93.  0.]
[   0. 1317.]
[ 0. 93.]
[1317.    0.]
[93.  0.]
[   0. 1317.]
[ 0. 93.]
[1317.    0.]
[93.  0.]
[   0. 1317.]
[ 0. 93.]
[1.317e+03 1.000e+00]
[93.  0.]
[1.000e+00 1.317e+03]
[ 0. 93.]
[1313.   43.]
[51.  4.]
[  43. 1313.]
[ 4. 51.]
[1317.   10.]
[84.  0.]
[  10. 1317.]
[ 0. 84.]
[147.   0.]
[10.  0.]
[  0. 147.]
[ 0. 10.]
[147.   0.]
[10.  0.]
[  0. 147.]
[ 0. 10.]
[147.   0.]
[10.  0.]
[  0. 147.]
[ 0. 10.]
[146.   0.]
[11.  0.]
[  0. 146.]
[ 0. 11.]
[146.   0.]
[11.  0.]
[  0. 146.]
[ 0. 11.]
[146.   0.]
[11.  0.]
[  0. 146.]
[ 0. 11.]
[146.   0.]
[11.  0.]
[  0. 146.]
[ 0. 11.]
[146.   0.]
[10.  0.]
[  0. 146.]
[ 0. 10.]
[143.   3.]
[7. 3.]
[  3. 143.]
[3. 7.]
[145.   1.]
[9. 1.]
[  1. 145.]
[1. 9.]
[1316.    0.]
[94.  0.]
[   0. 1316.]
[ 0. 94.]
[1316.    0.]
[94.  0.]


In [12]:
# # restore
#model = tf.keras.models.load_model('my_resnet_model.h5')

# # test
#img_path = "../my_nn/dataset/test/medicine/IMG_20190717_135408_BURST91.jpg"
#img_path = "../my_nn/dataset/test/glue/IMG_20190717_135425_BURST91.jpg"

#img = image.load_img(img_path, target_size=(224, 224))

#plt.imshow(img)
#img = image.img_to_array(img)/ 255.0
#img = np.expand_dims(img, axis=0)  # 为batch添加第四维

#print(model.predict(img))
#np.argmax(model.predict(img))

#save_path =("./tmp_TP_EP%d") % (1)
#fl=open(save_path, 'w')
#lists=[line+"\n" for line in all_TP_train]
#fl.writelines(lists)